=== SHRAVANIc01/SDL/info.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name = 'class'>
      <xs:complexType>
         <xs:sequence>
             <xs:element name = 'student' type = 'StudentType' minOccurs = '0' maxOccurs = 'unbounded' />
         </xs:sequence>
      </xs:complexType>
   </xs:element>

   <xs:complexType name = "StudentType">
      <xs:sequence>
         <xs:element name = "firstname" type = "xs:string"/>
         <xs:element name = "lastname" type = "xs:string"/>
         <xs:element name = "department" type = "xs:string"/>
         <xs:element name = "CGPA" type = "xs:string"/>
         <xs:element name = "Intern" type = "xs:string" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="PRN" type="xs:string" use="required"/>
   </xs:complexType>			 
</xs:schema>

=== SHRAVANIc01/SDL/info.xml
<?xml version="1.0" encoding="UTF-8"?>
<class
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="info.xsd">
	<student PRN = "393">
		<firstname>Dinkar</firstname>
		<lastname>Kad</lastname>
		<department>CS</department>
		<CGPA>8.5</CGPA>
		<Intern>TCS</Intern>
	</student>
	<student PRN = "493">
		<firstname>Vaneet</firstname>
		<lastname>Gupta</lastname>
		<department>IT</department>
		<CGPA>9.5</CGPA>
	</student>
	<student PRN = "593">
		<firstname>Jasvir</firstname>
		<lastname>Singh</lastname>
		<department>ENTC</department>
		<CGPA>9.0</CGPA>
	</student>
</class>
